### ISSUE TITLE
Lottie

### ISSUE THREAD

**Issue by hansmbakker** [AriaMinaei/theatre#14]
Nice tool! Can animations created in Theatre.js also be exported as [Lottie animations](https://airbnb.design/lottie/) so that they can be used in apps?

**Comment by vko-online** [comment]
that would be killer feature for mobile devs

**Comment by AriaMinaei** [comment]
I wonder what workflow you're envisioning with Lottie exports. Would you use Theatre.js animations both for web and for mobile for example?

**Comment by hansmbakker** [comment]
Lottie can be used in web, mobile and desktop apps. Both for micro-interactions and small explainer / filler animations.

Lottie animations can currently be created by Adobe software, but I'm looking for 2D animation software that I can use instead.

**Comment by AriaMinaei** [comment]
Thanks @hansmbakker. I took some time to think about this.

Native app support could have different forms, some of which may use Lottie.

* One way it could work is to have, say, a Figma plugin _plus_ Theatre extension that exports to Lottie. So the user would design the stills in Figma, and then use Theatre to animate them, and automatically get a Lottie export for native apps. That's one way to do it.
* Another way would be to _code_ the stills in React/Vue/etc, and have Theatre be the animating+tweaking step. This is how the [react-three-fiber](https://docs.theatrejs.com/r3f/) extension works.

I could think of other ways as well.

Luckily it's easy to experiment on theses with Theatre extensions<sup>1</sup> so we don't have to include Lottie support in the core, at least for now.

For those who want to build such an extension, feel free [to join the community](https://discord.gg/bm9f8F9Y9N) – we'd love to help!

---

1. As of now, extensions are [undocumented](https://docs.theatrejs.com/in-depth/#extensions), but I'm writing more docs soon.
