### ISSUE TITLE
Studio - mousewheel+shift on chrome windows always zooms out

### ISSUE THREAD

**Issue by RuiOrey** [AriaMinaei/theatre#19]
Hi, thanks for the amazing library, it is being ultra useful.
I'm facing an issue:

-  using the mousewheel + shift on the studio timeline seems to always zoom out

Was able to circumvent this by @AriaMinaei advice of dragging the lower scrollbar to scale and for now is good to go for me.
But anyway here is the bug report.
Thanks!

**Comment by AriaMinaei** [comment]
Thanks @RuiOrey. The behavior seems to be a bug with windows that I don't have the setup to reproduce right now.

If someone wants to contribute, the relevant line is [here](https://github.com/AriaMinaei/theatre/blob/995dcd97aae256b9e7d603af9fdd5252683b8949/theatre/studio/src/panels/SequenceEditorPanel/DopeSheet/Right/HorizontallyScrollableArea.tsx#L212).

**Comment by jmyrland** [comment]
I'm not able to reproduce this in chrome on windows. 

`shift+ scroll` slides the sequence viewport from right to left (which I assume is the correct behaviour):
![vSgMo4KN2K](https://user-images.githubusercontent.com/837651/135309500-b9c23e28-6fbc-4d4f-96c3-0ae7cbfe1ea7.gif)

However, the scrollbar on the bottom is not updated when `shift + scroll`-ing.

`ctrl + scroll` does work for zooming, but it is in my case a little "unpredictable":
![CTDS008UT3](https://user-images.githubusercontent.com/837651/135310506-ce388c2f-60d6-4771-b065-d457587a191c.gif)

As you can see, each time I zoom in using scroll (to be clear; in the example above, I'm scrolling 1 tick forward), it zooms in way to far. Zooming out seems to be working fine though.

**Comment by RuiOrey** [comment]
yes, sorry I was using `ctrl +scroll`, not `shift + scroll`.
yes that is what happens to me also using ctrl

**Comment by jmyrland** [comment]
> yes, sorry I was using ctrl +scroll, not shift + scroll.

No worries, I just wanted to clarify 👍 

Is this just an issue in windows though? 🤔 I don't have another device to test on atm, but it sounds wierd to me that this is an OS specific issue.

**Comment by jmyrland** [comment]
I was not able to reproduce your issue (always zooming out), as I am able to zoom in and out using `ctrl + scroll`. But the zooming is a little bit "off", as it does not seem to respect the "pivot point" at which you are zooming. I've tried fixing it, but to no avail 😢 

I have done one quality of life change (#30); when zooming outwards, it is now bounded to the sequence length. Previously, zooming outwards could be done "infinately", which causes some annoing issues. This is perticularly annoyng, as the "zoom-in" feature does not seem to respect the "pivot point". So to fix it, you have to manually drag the scrollbar:
![uaLZqXZXKc](https://user-images.githubusercontent.com/837651/135715641-43a57873-c537-4aae-bece-31f99a7d2669.gif)
