### ISSUE TITLE
Feature request: exposing a way to set gain after attaching audio to a sequence

### ISSUE THREAD

**Issue by jmyrland** [AriaMinaei/theatre#24]
It would be nice to have a way to change the gain for sequences with attached audio.

Possible solution already sketched by [@AriaMinaei on discord](https://discord.com/channels/870988717190426644/870988717190426647/893237080610709515).

**Comment by AriaMinaei** [comment]
Done in 4bf6f78a0021eeab783c93d753be75438b4d158f. Documentation: https://docs.theatrejs.com/in-depth/#sound-and-music
