### ISSUE TITLE
Clamp numerical ranges

### ISSUE THREAD

**Issue by akella** [AriaMinaei/theatre#31]
Would be nice to have this kind of flexible behaviour for ranges of numerical values:

1. Clamp numerical ranges on drag
2. Allow input of values out of range, when entering numbers from keyboard.

1) - Would allow for  better UX for designers or anybody figuring out perfect settings
2) would still allow developer to override values occasionally.

**Comment by AriaMinaei** [comment]
Added the clamp. Thanks @akella :)
