### ISSUE TITLE
Return sheetObject without reconfiguring

### ISSUE THREAD

**Issue by akre54** [AriaMinaei/theatre#480]
It would be nice if `sheet.object(key)` would return the `existingObject` if you didn't pass in a config. Right now we need to keep track of the objects in userland, which involves a bit of bookkeeping and state passing.

My use case is I'm trying to set the studio selection, and you need the sheetObject to do this. Most places I already have access to the Sheet through a Provider, and I use string keys for everything else. Is this doable? Thanks!

**Comment by vimlesh1975** [comment]
Or something like
sheet.getObject(key)

**Comment by AriaMinaei** [comment]
@akre54 yolo'd this one. Upgrade to `0.7.1` and use `sheet.__experimental_getExistingObject('key')`.
