### ISSUE TITLE
Need understanding how we can use types.image in case of three.js

### ISSUE THREAD

**Issue by RaishavHanspal** [AriaMinaei/theatre#483]
I'm trying to link the `types.image` theatre property to work with my MeshStandardMaterial `map` property, Could you suggest this is viable/feasible with the current implementation.

the `onValuesChanges` function return object in form 
```json
{ id: string; type: "image" }
```
The id only shows the image name.
There is a suggestion in the Docs: that a custom interpolator might be required, please give insights on the usage?

Another thing: https://theatre-playground.vercel.app/shared/dom is down.

**Comment by Raishav** [comment]
Hi @AriaMinaei, could you please suggest on above?
Thanks :)

**Comment by RaishavHanspal** [comment]
Hi @AriaMinaei, 
Could you please suggest on this?
Thanks :)

**Comment by AriaMinaei** [comment]
Looks like the link that is supposed explain this is broken. [Here](https://www.theatrejs.com/docs/latest/api/core#project.getasseturl_assethandle_) it is.

Basically:
```ts
onst object = sheet.object('My Object', {
  texture: types.image(undefined, {
    label: 'Texture',
  }),
})

object.onValuesChange(({ texture }) => {
  setImageUrl(project.getAssetUrl(texture))
})
```
