### ISSUE TITLE
Is this UI interface created using React? What should I do if I want to customize the use of Vue development on top of that

### ISSUE THREAD

**Issue by WREQI** [AriaMinaei/theatre#484]
Is this UI interface created using React? What should I do if I want to customize the use of Vue development on top of that
![image](https://github.com/theatre-js/theatre/assets/35467304/40abdb3c-02ba-4839-9ea3-575f7f5f24a2)

**Comment by AriaMinaei** [comment]
Yup, the UI is made in React.

You can't change the core UI components (like the sequence editor) with Vue. You'll need to do that in React.

_But_, you can add toolbars and new panels and write them in Vue. This [tutorial](https://www.theatrejs.com/docs/latest/manual/authoring-extensions) should get you started.
